### ISSUE TITLE
Docker stops responding after about 12 days

### ISSUE THREAD

**Issue by fluffyegg** [ideal-postcodes/postcodes.io#627]
Hi! First off – thank you for your work on this, it's a great resource.

We're running the Docker on a production server and find that after about 12 days, it stops responding and gives a 500 Error: 

`500 Server Error.\nFor an urgent fix email support@ideal-postcodes.co.uk. \nAlternatively submit an issue at https://github.com/ideal-postcodes/postcodes.io/issues\n" `

We added restart: always to the docker-compose.yml but this doesn't seem to have made a difference.

It seems to be the database container that goes down – it disappears from the list in _docker ps_ – if this is of any help?

**Comment by cblanc** [comment]
Would you be able to share your docker-compose.yml?

**Comment by fluffyegg** [comment]
Yes, docker-compose.yml below. I should also note that the Docker does exactly the same on our local development machines. The only common link is that both are running Ubuntu 18.04.

```
---
version: '3'
services:
  api:
    image: idealpostcodes/postcodes.io:latest
    depends_on:
      - db
    environment:
      - POSTGRES_DATABASE=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
    restart: always
  db:
    image: idealpostcodes/postcodes.io.db:latest
    environment:
      - POSTGRES_DB=postcodesiodb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postcodesio

```

**Comment by cblanc** [comment]
Is it possible to retrieve the logs for the closed DB container? 

We run something similar to power postcodes.io, also on Ubuntu 18.04. Have been using this setup for ~17 months without the DB container disappearing

The DB container is configured identically

```yaml
---
version: '3'
services:
  api:
    image: idealpostcodes/postcodes.io:release-12.0.3
    restart: always
    depends_on:
      - db
    logging:
      # ...
    environment:
      # ...
    ports:
      - 8000:8000
  db:
    image: idealpostcodes/postcodes.io.db:12.0.3
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DATABASE:
```

May be worth pinning the version perhaps from latest to something like 12.0.3?
